### ISSUE TITLE
SSR Hydration issue

### ISSUE THREAD

**Issue by folamy** [craigrileyuk/vue3-mq#9] opened 2021-07-26 08:09 UTC
Hi @craigrileyuk ,
I am getting this error:

[Vue warn]: Hydration node mismatch:
- Client vnode: div 
- Server rendered DOM: 

 <empty string> 
  at MqResponsive target="md+"

**Comment by craigrileyuk** [comment] 2021-07-26 08:45
Hi @folamy,

Do you have a reproduction of this issue? How are you doing the SSR?

**Comment by folamy** [comment] 2021-07-26 09:48
> Hi @folamy,
> 
> Do you have a reproduction of this issue? How are you doing the SSR (which framework, if any)?
> 
> Also, I need to document this, but for SSR, you can use:
> 
> ```js
> app.use(Vue3Mq, {
>     defaultBreakpoint: "xl"
> }
> ```
> 
> as well to tell the SSR renderer which breakpoint to use.

No, I don't have a reproduction repo yet, but this is what my code looks like

````js
import { createSSRApp } from 'vue'
import { createRouter } from '../router/index'
import { MqResponsive, Vue3Mq } from 'vue3-mq'
import { naive } from '../naive/components'

export { createApp }

function createApp ({ Page }) {
  const app = createSSRApp(Page)
  const router = createRouter()
  app.component('MqResponsive', MqResponsive)
  app.use(naive)
  app.use(Vue3Mq, {
    breakpoints: {
      xs: 0,
      sm: 600,
      md: 1024,
      lg: 1440,
      xl: 1920,
      xxl: Infinity
    },
    defaultBreakpoint: "xl"
  })
  app.use(router)
  return { app, router }
}
````
I had to hard code MqResponsive to be able to use `<mq-responsive>....</mq-responsive>` else,
`[Vue warn]: Failed to resolve component: mq-responsive`

**Comment by craigrileyuk** [comment] 2021-07-26 11:56
> I had to hard code MqResponsive to be able to use `<mq-responsive>....</mq-responsive>` else,
> `[Vue warn]: Failed to resolve component: mq-responsive`

This part is intentional. Given the modularity of Vue3, the ecosystem is moving away from global properties, components and functions in favour of importing things as required. (see the [Vue3 MQ Version 3 Migration Guide](https://vue3-mq.info/#/migration-guide-v2-to-v3) )

You can, of course, register the MqResponsive component globally as you have done here.

I'll investigate the SSR hydration issue and see what I can do. Thanks for the feedback.

**Comment by folamy** [comment] 2021-07-30 15:16
@craigrileyuk,
Is there any update on the ssr hydration?

**Comment by craigrileyuk** [comment] 2021-08-01 18:06
I've hooked up vue3-mq with my local implementation of Laravel/Vue3/InertiaSSR and there's no console warnings.

I'll have to see if I can try a Vue3 SSR app when I get time.

**Comment by sebsasto** [comment] 2021-08-18 08:15
Hey @folamy and @craigrileyuk 

I was having the same issue and basically it happens because the mismatch between the server (default breakpoint) and the client (actual breakpoint). Let's say the actual breakpoint is xs but because in the server you render everything as xl. There will be inconsistency in client and server causing the hydration problem.

The solution is to rehydrate the component after they are mounted. You can do it in two ways: using a mixin in the installation of the plugin (is you want to use the custom components) or you can do it in the `useMq` composable if you only use the mq state.

For option one in the plugins installation you have to do:

```javascript
let hasSetupListeners = false;
app.mixin({
   mounted() {
     if (!hasSetupListeners) {
       updateBreakpoints({ breakpoints, preset });
       hasSetupListeners = true;
     }
   },
});
```

In the meantime while @craigrileyuk fixes this in the plugin itself if you are using the composable option what you can do is to create a custom `useMq()` instead of the provided by the plugin.

What I did was:

```javascript
function getOnMounted() {
  let hasSetupListeners = false;
  return () => {
    onMounted(() => {
      if (!hasSetupListeners) {
        updateBreakpoints({ breakpoints, preset });
        hasSetupListeners = true;
      }
    });
  };
}

const injectOnMounted = getOnMounted();

export function injectMq() {
  injectOnMounted();
  const mq = inject('mq');
  if (!mq) throw new Error('MQ3 is not installed.');
  else return mq;
}
```

Hope this help solving the issue

**Comment by craigrileyuk** [comment] 2021-08-20 13:31
> Hope this help solving the issue

Thanks for the advice there @sebsasto. I haven't forgotten this. It's just something of a balancing act since you obviously want SSR to render according to the default breakpoint, but then on the client, you need to switch to the breakpoint of the client. 

You could render the page with the default breakpoint first before then switching to the client breakpoint, but this would give everyone a major content flash upon page load. So I'll have to do some research to find the best way to proceed.

**Comment by loremru** [comment] 2022-01-11 17:04
Hey @craigrileyuk is there any news? How to use vue3-mq with nuxt 3? I have an error:
`Error while mounting app: Error: Vue3Mq is not installed in this app. Please follow the installation instructions and try again.`

**Comment by craigrileyuk** [comment] 2022-01-11 19:15
> I have an error: `Error while mounting app: Error: Vue3Mq is not installed in this app. Please follow the installation instructions and try again.`

This is not connected with this issue. That error is usually a result of not following the instructions properly to install the plugin:

```js
import { createApp } from "vue";
import { Vue3Mq } from "vue3-mq";

const app = createApp({});

app.use(Vue3Mq)

app.mount('#app');
```

**Comment by loremru** [comment] 2022-01-12 11:18
@craigrileyuk But I have the same code. Did you test it?
![image](https://user-images.githubusercontent.com/66596500/149130431-de3bcc54-e23c-415d-86a5-fc029b357fd6.png)

**Comment by craigrileyuk** [comment] 2022-01-12 18:27
> @craigrileyuk But I have the same code. Did you test it?

Yep. Fresh Nuxt3 install. Created a plugins/vue3-mq.js file and used the above code.

It still gets the hydration issue that this thread discusses, but it works with SSR.

**Closed** 2022-04-10 17:06 UTC

**Comment by jbrundagejr** [comment] 2022-09-07 15:26
Hey @craigrileyuk - thanks for such a great package! I'm still getting this hydration warning even though I see the issue is closed and the docs are still the same. Any suggestions?

**Comment by Bohdan909** [comment] 2023-08-02 17:15
Hello, @craigrileyuk.
is there any news with hydration problem when the server default breakpoint does not match  with the client  breakpoint?

**Comment by craigrileyuk** [comment] 2023-08-07 04:48
It's not something that's fixable really. The hydration mismatch is the fix and Vue does it automatically.

Basically you're telling the server to render HTML with one structure and the client to render HTML with another structure. There's no way around that without involving the backend.

You could get your backend to provide the screen width to your ssr script based on user agent analysis and use that to set the default breakpoint, but that would be way beyond the scope of a frontend Vue package like this.

**Comment by Bohdan909** [comment] 2023-08-09 12:59
@craigrileyuk, so the plugin is not usable for Nuxt?

If my defaultBreakpoint: 'desktop' and I load page on 'mobile' breakpoint, then mq does not work :(

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')`

**Comment by Bohdan909** [comment] 2023-08-09 13:27
With classes switcher vue3-mq also not working correct:

<div :class="['menu-wrap fx', {
        'fx-col fx-jc-sb': mq.desktop
      }]">
      
 If defaultBreakpoint: 'desktop' and I load page on 'mobile' breakpoint condition` 'fx-col fx-jc-sb': mq.desktop` not work :(

**Comment by craigrileyuk** [comment] 2023-08-10 03:55
@Bohdan909 - This issue is regarding a hydration warning this results when the defaultBreakpoint on the server mismatches the read breakpoint on the client.

Your issue sounds like something completely different. If it persists, can you please open a new issue and post steps to reproduce the issue (Nuxt version, Vue version, installation method, config, code sample etc)
